### 1. 車種データの生成

In [178]:
import pandas as pd
import random

preferred_color  = [ '赤', '青', '黒', '白', 'シルバー', '緑', '黄色' ]
color_option = preferred_color
new_type = [0, 1]

# トヨタの代表的な車種とそれぞれの特徴
toyota_cars = [
    {'id': 1, 'モデル': 'Corolla', '価格': 218, '燃費': 30, '馬力': 132, 'タイプ': 'Sedan','新車':1, '概要': 'Reliable compact car, great fuel efficiency'},
    {'id': 2, 'モデル': 'Camry', '価格': 350, '燃費': 28, '馬力': 203, 'タイプ': 'Sedan', '新車':1,'概要': 'Spacious and comfortable midsize sedan'},
    {'id': 3, 'モデル': 'Prius', '価格': 275, '燃費': 50, '馬力': 121, 'タイプ': 'Hatchback','新車':1, '概要': 'Eco-friendly hybrid with outstanding fuel economy'},
    {'id': 4, 'モデル': 'Aqua', '価格': 300, '燃費': 40, '馬力': 100, 'タイプ': 'Hatchback', '新車':1, '概要': 'Compact hybrid, excellent city car'},
    {'id': 5, 'モデル': 'RAV4', '価格': 295, '燃費': 25, '馬力': 203, 'タイプ': 'SUV', '新車':1, '概要': 'Versatile SUV, suitable for families'},
    {'id': 6, 'モデル': 'Land Cruiser', '価格': 370, '燃費': 13, '馬力': 381, 'タイプ': 'SUV', '新車':1, '概要': 'Luxury SUV with off-road capabilities'},
    {'id': 7, 'モデル': 'Yaris', '価格': 200, '燃費': 32, '馬力': 106, 'タイプ': 'Hatchback', '新車':1, '概要': 'Affordable and reliable subcompact car'},
    {'id': 8, 'モデル': 'Supra', '価格': 500, '燃費': 24, '馬力': 335, 'タイプ': 'Sports', '新車':1, '概要': 'High-performance sports car with sleek design'},
    {'id': 9, 'モデル': 'C-HR', '価格': 265, '燃費': 27, '馬力': 144, 'タイプ': 'SUV', '新車':1, '概要': 'Stylish compact crossover with unique design'},
    {'id': 10, 'モデル': 'Harrier', '価格': 315, '燃費': 26, '馬力': 295, 'タイプ': 'SUV', '新車':1, '概要': 'Comfortable and stylish midsize crossover'},
    {'id': 11, 'モデル': 'Century', '価格': 2000, '燃費': 20, '馬力': 381, 'タイプ': 'Luxury', '新車': 1, '概要': 'Exclusive luxury sedan with classic design'},
    {'id': 12, 'モデル': 'Lexus LS', '価格': 1200, '燃費': 22, '馬力': 415, 'タイプ': 'Luxury', '新車': 1, '概要': 'Flagship luxury sedan with advanced technology'},
    {'id': 13, 'モデル': 'Lexus LC', '価格': 1400, '燃費': 25, '馬力': 471, 'タイプ': 'Sports', '新車': 1, '概要': 'High-performance luxury coupe with stunning aesthetics'},
    {'id': 14, 'モデル': 'GR Supra RC', '価格': 750, '燃費': 18, '馬力': 500, 'タイプ': 'Racing', '新車': 1, '概要': 'Track-focused racing version of the Supra with enhanced performance'}
]

# cars = pd.DataFrame(toyota_cars)

cars_data = []
id_counter = 1
for car in toyota_cars:
    for c in color_option:
        for n in new_type:
            if n == 1:
                car_copy = car.copy()
                car_copy['id'] = id_counter
                car_copy['色'] = c
                car_copy['新車'] = 1
                cars_data.append(car_copy)
                
            elif n == 0:
                car_copy = car.copy()
                car_copy['価格'] = car_copy['価格']*0.7
                car_copy['id'] = id_counter
                car_copy['色'] = c
                car_copy['新車'] = 0
                
            cars_data.append(car_copy)
            id_counter += 1

cars_df = pd.DataFrame(cars_data)
cars_df = cars_df.drop_duplicates().reset_index(drop=True)
# データフレームをCSVファイルとして保存
cars_df.to_csv('cars.csv', index=False)

In [195]:
cars_df

,id,モデル,価格,燃費,馬力,タイプ,新車,概要,色
0,1,Corolla,152.6,30,132,Sedan,0,"Reliable compact car, great fuel efficiency",赤
1,2,Corolla,218.0,30,132,Sedan,1,"Reliable compact car, great fuel efficiency",赤
2,3,Corolla,152.6,30,132,Sedan,0,"Reliable compact car, great fuel efficiency",青
3,4,Corolla,218.0,30,132,Sedan,1,"Reliable compact car, great fuel efficiency",青
4,5,Corolla,152.6,30,132,Sedan,0,"Reliable compact car, great fuel efficiency",黒
...,...,...,...,...,...,...,...,...,...
191,192,GR Supra RC,750.0,18,500,Racing,1,Track-focused racing version of the Supra with...,シルバー
192,193,GR Supra RC,525.0,18,500,Racing,0,Track-focused racing version of the Supra with...,緑
193,194,GR Supra RC,750.0,18,500,Racing,1,Track-focused racing version of the Supra with...,緑
194,195,GR Supra RC,525.0,18,500,Racing,0,Track-focused racing version of the Supra with...,黄色
195,196,GR Supra RC,750.0,18,500,Racing,1,Track-focused racing version of the Supra with...,黄色

### 2.顧客データの生成

In [241]:
import pandas as pd
import random

# 家族構成のオプション
#family_type = ['独身', '家族あり（子供なし）', '子供1人', '子供2人', '子供3人以上']

tokyo_city = [
    '千代田区', '中央区', '港区', '新宿区', '文京区', '台東区', '墨田区', '江東区', '品川区', '目黒区', 
    '大田区', '世田谷区', '渋谷区', '中野区', '杉並区', '豊島区', '北区', '荒川区', '板橋区', '練馬区', 
    '足立区', '葛飾区', '江戸川区', '八王子市', '立川市', '武蔵野市', '三鷹市', '青梅市', '府中市', '昭島市', 
    '調布市', '町田市', '小金井市', '小平市', '日野市', '東村山市', '国分寺市', '国立市', '福生市', '狛江市', 
    '東大和市', '清瀬市', '東久留米市', '武蔵村山市', '多摩市', '稲城市', '羽村市', 'あきる野市', '西東京市'
]

occupation_type = [
'会社役員', '会社員', 'パートタイマー', '団体職員', 'フリーランス', '学生', '医師', '士業', '家事手伝い', '無職'
]

preferred_type = ['Sedan', 'SUV', 'Hatchback', 'Sports', 'Luxury']

preferred_color  = [ '赤', '青', '黒', '白', 'シルバー', '緑', '黄色' ]


# 顧客データの生成
num_customers = 2000
customers_df = pd.DataFrame({
    'id': range(1, num_customers + 1),
    '年齢': [random.randint(18, 70) for _ in range(num_customers)],
    '性別': [random.choice(['男性', '女性']) for _ in range(num_customers)],
    '職業': [random.choice(occupation_type) for _ in range(num_customers)],
    '在住': [random.choice(tokyo_city) for _ in range(num_customers)],
    '世帯数': [random.randint(1, 7) for _ in range(num_customers)],
    'タイプ': [random.choice(preferred_type) for _ in range(num_customers)],
    '色': [random.choice(preferred_color) for _ in range(num_customers)],
    '新車':[random.choice(new_type) for _ in range(num_customers)]
})

# 車種データの読み込み
#cars = pd.read_csv('cars.csv')


def assign_max_price(occupation):
    # 職業に応じた価格範囲を設定
    if occupation in ['会社役員', '医師', '士業']:
        # 高収入職種
        return random.randint(700, 1500)
    elif occupation in ['会社員', 'フリーランス', '団体職員']:
        # 中収入職種
        return random.randint(400, 700)
    elif occupation in ['パートタイマー', '学生', '家事手伝い']:
        # 低収入職種
        return random.randint(100, 400)
    else:
        # その他（無職など）
        return random.randint(100, 500)

# 顧客データに '購入希望価格 最大' 列を追加
customers_df['価格'] = customers_df['職業'].apply(assign_max_price)


# CSVファイルとして保存
customers.to_csv('customers.csv', index=False)

In [181]:
customers.head(5)

   id  年齢  性別       職業    在住  世帯数     タイプ     色  新車   価格
0   1  64  男性       士業   品川区    2     SUV     白   0  795
1   2  27  女性  パートタイマー   調布市    2  Luxury    黄色   1  154
2   3  69  女性       医師  小金井市    2  Sports     白   1  725
3   4  20  男性  パートタイマー   立川市    3  Luxury     黒   0  178
4   5  62  女性       無職   目黒区    1     SUV  シルバー   0  113

### 3. 購入履歴データの生成

In [242]:
import pandas as pd
import random
from datetime import datetime, timedelta

# 顧客データと車種データの読み込み
customers = pd.read_csv('customers.csv')
cars = pd.read_csv('cars.csv')

# 購入履歴データの生成
num_purchases = 10000  # 生成する購入履歴の数
purchase_history = []

for _ in range(num_purchases):
    customer = customers.sample().iloc[0]
    car = cars.sample().iloc[0]

    # 購入日をランダムに生成
    purchase_date = datetime(2013, 1, 1) + timedelta(days=random.randint(0, 365))

    purchase_record = {
        'customer_id': customer['id'],
        'car_id': car['id'],
        '購入日': purchase_date.strftime('%Y-%m-%d'),
        '満足度': random.randint(1, 3)  # 1から10の評価
    }
    purchase_history.append(purchase_record)

purchase_history_df = pd.DataFrame(purchase_history)

# CSVファイルとして保存
purchase_history_df.to_csv('purchase_history.csv', index=False)

In [243]:
purchase_history_df.head(5)

   customer_id  car_id         購入日  満足度
0         1175     175  2013-08-20    3
1          661     164  2013-06-01    2
2          773     154  2013-12-20    3
3          763     127  2013-12-09    3
4          193     175  2013-01-11    2

## 推薦モデル

#### ステップ 1: データの準備  
購入履歴データ（purchase_history.csv）を読み込みます。  
車種データ（cars.csv）と顧客データ（customers.csv）も読み込みます。

In [244]:
purchase_history = pd.read_csv('purchase_history.csv')
cars = pd.read_csv('cars.csv')
customers = pd.read_csv('customers.csv')

In [245]:
customers

        id  年齢  性別       職業    在住  世帯数        タイプ     色  新車    価格
0        1  64  男性       士業   品川区    2        SUV     白   0   795
1        2  27  女性  パートタイマー   調布市    2     Luxury    黄色   1   154
2        3  69  女性       医師  小金井市    2     Sports     白   1   725
3        4  20  男性  パートタイマー   立川市    3     Luxury     黒   0   178
4        5  62  女性       無職   目黒区    1        SUV  シルバー   0   113
...    ...  ..  ..      ...   ...  ...        ...   ...  ..   ...
1995  1996  69  男性       士業   狛江市    3     Luxury     白   1  1211
1996  1997  35  女性   フリーランス    北区    3      Sedan  シルバー   0   408
1997  1998  48  男性       医師   稲城市    6  Hatchback     赤   0   956
1998  1999  61  女性      会社員   新宿区    6        SUV     青   1   510
1999  2000  32  男性   フリーランス   渋谷区    3     Sports     黒   1   408

[2000 rows x 10 columns]

#### ステップ 2: 協調フィルタリングモデルの訓練  
Surprise ライブラリを使用して、協調フィルタリングモデルを訓練します。  
データをトレーニングセットとテストセットに分割します。

In [246]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split
from surprise.accuracy import rmse
import pandas as pd

# 購入履歴データを読み込み
purchase_data = pd.read_csv('purchase_history.csv')

# Surprise ライブラリ用のデータセットを作成
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(purchase_data[['customer_id', 'car_id', '満足度']], reader)

# データをトレーニングセットとテストセットに分割
trainset, testset = train_test_split(data, test_size=0.25)

# SVD（Singular Value Decomposition）を使った協調フィルタリングモデルの訓練
algo = SVD()
algo.fit(trainset)

# 希望価格の範囲に応じた推薦を行う関数
def svd_collaborative_recommend_with_budget_range(new_customer, algo, cars_df):
    # 顧客の希望価格の範囲を取得
    price_range = new_customer['価格']
    min_price = price_range *0.8
    max_price = price_range *1.1

    # 希望価格範囲内の車種に対する推薦スコアを計算
    car_ids = cars_df['id']
    predicted_ratings = []
    for car_id in car_ids:
        car_price = cars_df.loc[cars_df['id'] == car_id, '価格'].values[0]
        if min_price <= car_price <= max_price:
            predicted_rating = algo.predict(new_customer['id'], car_id).est
            predicted_ratings.append((car_id, predicted_rating))

    # トップ5の推薦車種を選択
    top_recommendations = sorted(predicted_ratings, key=lambda x: x[1], reverse=True)[:5]
    recommended_cars = cars_df[cars_df['id'].isin([car_id for car_id, _ in top_recommendations])]
    return recommended_cars

In [247]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from surprise import SVD, Dataset, Reader
from surprise.model_selection import train_test_split

# 顧客データと購入履歴データの読み込み
customers = pd.read_csv('customers.csv')
purchase_history = pd.read_csv('purchase_history.csv')
cars = pd.read_csv('cars.csv')

# SVDモデルの訓練
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(purchase_history[['customer_id', 'car_id', '満足度']], reader)
trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)



# 新規顧客と既存顧客間の類似性を計算する関数
def calculate_similarity(new_customer, customers_df):
    # 顧客特徴のベクトル化（例: 年齢、性別、職業など）
    # 注意: 実際のデータに適合するように調整する必要があります
    customer_features = np.array(customers_df[['年齢', '性別', '職業']])
    new_customer_features = np.array(new_customer[['年齢', '性別', '職業']])
    similarities = cosine_similarity(new_customer_features, customer_features)
    return similarities

# 類似した顧客が選んだ車種を推薦する関数
def recommend_based_on_similar_customers(new_customer, customers_df, purchase_history_df, cars_df, algo, top_n=5):
    similarities = calculate_similarity(new_customer, customers_df)
    most_similar_customer_idx = np.argmax(similarities)
    most_similar_customer_id = customers_df.iloc[most_similar_customer_idx]['id']

    # 顧客の希望価格範囲を取得
    min_price = new_customer['価格']*0.8
    max_price = new_customer['価格']*1.1

    # 類似顧客が購入した車種を抽出
    purchased_car_ids = purchase_history_df[purchase_history_df['customer_id'] == most_similar_customer_id]['car_id'].unique()

    # SVDを使ってスコアリングし、価格範囲内の車種のみを選択
    predicted_ratings = []
    for car_id in purchased_car_ids:
        car_price = cars_df.loc[cars_df['id'] == car_id, '価格'].values[0]
        if min_price <= car_price <= max_price:
            predicted_rating = algo.predict(new_customer['id'], car_id).est
            predicted_ratings.append((car_id, predicted_rating))

    top_recommendations = sorted(predicted_ratings, key=lambda x: x[1], reverse=True)[:top_n]
    recommended_car_ids = [car_id for car_id, _ in top_recommendations]

    # 推薦された車種を返す
    recommended_cars = cars_df[cars_df['id'].isin(recommended_car_ids)]
    return recommended_cars

# 新規顧客のデータ
# new_customer = pd.DataFrame({'id': [999], '年齢': [30], '性別': [1], '職業': [2], '希望価格最小': [200], '希望価格最大': [300]})

# 推薦を生成
#recommended_cars = recommend_based_on_similar_customers(new_customer, customers, purchase_history, cars, algo)
#print(recommended_cars)

In [248]:
# テストセットで予測を行い、精度（例: RMSE）を計算
predictions = algo.test(testset)
accuracy = rmse(predictions)

RMSE: 0.6293

#### ステップ 3: コンテンツベースフィルタリングの実装  
顧客の好みに基づいて車種を推薦するコンテンツベースフィルタリングを実装します。

In [253]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 車種の特徴ベクトルを作成
def create_car_features(cars_df):
    # 特徴として「タイプ、色、価格、新車」を組み合わせる
    cars_df['features'] = cars_df.apply(lambda x: f"{x['タイプ']} {x['色']}{x['価格']} {x['新車']}", axis=1)
    return cars_df

# TF-IDF ベクトルの作成
cars_df = create_car_features(cars_df)
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(cars_df['features'])

# 顧客の好みに基づいて車種を推薦
def content_based_recommend(new_customer, cars_df):
    # 顧客の好みの特徴ベクトルを作成
    customer_pref = f"{new_customer['タイプ']} {new_customer['色']} {new_customer['価格']} {new_customer['新車']}"
    customer_pref_vector = tfidf.transform([customer_pref])

    # 類似度スコアの計算
    cosine_sim = cosine_similarity(customer_pref_vector, tfidf_matrix)
    #print(cosine_sim)
    
    # スコアに基づいて車種を推薦
    top_matches = cosine_sim.argsort()[0][-5:][::-1]
    recommended_cars = cars_df.iloc[top_matches]
    return recommended_cars

#### ステップ 4: ハイブリッド推薦システムの実装  
協調フィルタリングとコンテンツベースフィルタリングの結果を組み合わせるハイブリッド推薦システムを実装します。

In [254]:
def hybrid_recommendation(customer, algo, cars_df,customers_df, purchase_history_df, top_n=5):
    content_recommendations = content_based_recommend(customer, cars_df)
    #collaborative_recommendations = collaborative_recommend(customer, algo, cars_df)
    #collaborative_recommendations =  svd_collaborative_recommend_with_budget_range(customer, algo, cars_df)
    collaborative_recommendations =  recommend_based_on_similar_customers(customer, customers_df, purchase_history_df, cars_df, algo, top_n)
    # 両方の方法から得られた推薦を組み合わせる（例: 重複排除）
    final_recommendations = pd.concat([content_recommendations, collaborative_recommendations]).drop_duplicates().head(top_n)

    return final_recommendations

#### ステップ 5: ハイブリッドモデルの評価  
テストセットを使用して、ハイブリッドモデルの精度を評価します。

In [255]:
def display_customer_details(customer):
    print(f"顧客ID: {customer['id']}")
    print(f"年齢: {customer['年齢']}, 性別: {customer['性別']}, 職業: {customer['職業']}, 住所: {customer['在住']}")
    print(f"価格: {customer['価格']}, タイプ: {customer['タイプ']}, 色: {customer['色']}")

def display_purchased_cars_details(purchased_car_ids, cars_df):
    purchased_cars = cars_df[cars_df['id'].isin(purchased_car_ids)]
    for _, car in purchased_cars.iterrows():
        print(f"購入車種: {car['モデル']}, 価格: {car['価格']}, タイプ: {car['タイプ']}, 色: {car.get('色', 'N/A')}")

def display_recommended_cars_details(recommended_cars):
    for _, car in recommended_cars.iterrows():
        print(f"推薦車種: {car['モデル']}, 価格: {car['価格']}, タイプ: {car['タイプ']}, 色: {car.get('色', 'N/A')}")

def test_recommendations(test_customers, algo, cars_df, customers_df, purchase_history_df, top_n=5):
    for _, customer in test_customers.iterrows():
        actual_purchased_cars = purchase_history[purchase_history['customer_id'] == customer['id']]['car_id'].tolist()
        recommended_cars = hybrid_recommendation(customer, algo, cars_df, customers_df, purchase_history_df, top_n)

        display_customer_details(customer)
        #display_purchased_cars_details(actual_purchased_cars, cars_df)
        display_recommended_cars_details(recommended_cars)
        print("\n")


#入力データをワンホット化しないといけない。、。


test_customers = customers.sample(10)
test_recommendations(test_customers, algo, cars_df, customers_df, purchase_history_df, top_n=5)

ValueError: could not convert string to float: '男性'